language: c
compiler:
 - gcc
 - clang
before_script:
 - sudo apt-get install libldns-dev
 - git clone https://github.com/jedisct1/libsodium.git --branch=1.0.2
 - cd libsodium
 - ./autogen.sh
 - ./configure --disable-dependency-tracking
 - sudo make install
 - sudo ldconfig
 - cd ..
 - ./autogen.sh
 - ./configure --disable-dependency-tracking --enable-plugins
script:
 - make -j$(nproc)
matrix:
 - fast_finish: true
