dist: trusty
sudo: required

language: c

services:
 - docker

compiler:
 - gcc

before_install:
 - sudo apt-get install -y libldns-dev libsystemd-dev libsodium-dev
 - git clone https://github.com/jedisct1/libsodium.git --branch=stable
 - ./autogen.sh
 - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
 - ./configure --with-systemd && make -j$(nproc) install
 - env IPV4_ONLY=yes ./contrib/resolvers-check.sh
 - make uninstall
 - make distclean

 - docker run --rm -v $(pwd):/workdir multiarch/alpine:x86-edge    /workdir/.travis.sh
 - docker run --rm -v $(pwd):/workdir multiarch/alpine:armhf-edge  /workdir/.travis.sh
 - docker run --rm -v $(pwd):/workdir multiarch/alpine:x86_64-edge /workdir/.travis.sh

 - docker run --rm -v $(pwd):/workdir pritunl/archlinux:latest     /workdir/dist-build/win32-win64-xcompile.sh

matrix:
 - fast_finish: true
